[versions]
agp = "8.13.0"
desugar = "2.1.5"
dependencyAnalysis = "3.0.4"
kotlin = "2.2.20"
ktfmt = "0.58"
detekt = "1.23.8"
kover = "0.9.2"
spotless = "8.0.0"
jdk = "24"
jdkTarget = "17"
sort = "0.15"

[plugins]
convention-kotlin = { id = "dev.whosnickdoglio.convention.kotlin", version = "0.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
lint = { id = "com.android.lint", version.ref = "agp" }
android-app = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
doctor = { id = "com.osacky.doctor", version = "0.12.1" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version = "2.2.20-2.0.3" }
sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "sort" }
burst = { id = "app.cash.burst" }

[libraries]
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

# Only present to trigger automatic renovate updates
ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }

junit = { module = "junit:junit", version = "4.13.2" }
burst = { module = "app.cash.burst:burst-gradle-plugin", version = "2.10.2" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.1" }
